### ISSUE TITLE
"Start Building Your Own ERC-721 Token" links don't work

### ISSUE THREAD

**Issue by mertcelebi** [0xProject/erc721-website#5] opened 2018-02-23 04:19 UTC

**Comment by tomhschmidt** [comment] 2018-02-23 05:46
as intended right now, unfortunately. The spec is like 95% -- still hashing out the last few bits in EIP 841 and https://gitter.im/ETH-NFT and then waiting for OpenZeppelin contracts to land so we have something to link to. I'll add those links when we have them (EOW next week) and close this out then.

**Comment by tomhschmidt** [comment] 2018-03-23 18:43
Fixed with https://github.com/0xProject/erc721-website/commit/83d9875bf8cdde007c1009a81796ceb2bb7c36e4

**Closed by tomhschmidt** 2018-03-23 18:43 UTC

**Comment by fulldecent** [comment] 2018-03-24 03:39
STOP WARNING BAD NO.

There's a (small) problem with the Zeppelin implementation. Don't link to it right now. Reopen this issue. I'll open an issue on that repo.

**Comment by fulldecent** [comment] 2018-03-24 03:43
Or add warning is fine too:

> There may be some issues with this implementation
